backend:
  name: git-gateway

media_folder: static/media
public_folder: /media

slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - label: Contenido páginas
    name: pages
    editor:
      preview: false
    files:
      - label: Cabecera y pie
        name: header
        file: src/data/pages/header.md
        fields:
          - label: Teléfono
            name: phone
            widget: string
          - label: Dirección
            name: address
            widget: string
          - label: Dossier
            name: dossier
            widget: object
            fields:
              - label: Título
                name: title
                widget: string
              - label: Fichero
                name: file
                widget: file
          - label: Redes Sociales
            name: social
            widget: list
            fields:
              - label: Red
                name: network
                widget: select
                options: ["twitter", "facebook", "instagram"]
                default: twitter
              - label: URL
                name: url
                widget: string
              - label: Usuario
                name: handle
                widget: string
      - label: Portada
        name: frontpage
        file: src/data/pages/index.md
        fields:
          - label: Template
            name: template
            widget: hidden
            default: frontpage
          - label: Título
            name: title
            widget: string
          - label: Descripción SEO
            name: seo_description
            widget: string
            required: false
          - label: Imagen SEO
            name: seo_image
            widget: image
            required: false
          - label: Entradilla
            name: tagline
            widget: markdown
          - label: Proyectos Destacados
            name: related_projects
            widget: list
            fields:
              - label: Proyecto
                name: project
                widget: relation
                collection: projects
                searchFields: ["title"]
                valueField: title
                displayFields: ["title"]
          - label: Entradilla servicios
            name: services_intro
            widget: markdown
          - label: Entradilla empresa
            name: company_intro
            widget: markdown
          - label: Imagen empresa
            name: company_picture
            widget: image
      - label: Proyectos
        name: projects
        file: src/data/pages/proyectos.md
        fields:
          - label: Template
            name: template
            widget: hidden
            default: projects
          - label: Título
            name: title
            widget: string
          - label: Descripción SEO
            name: seo_description
            widget: string
            required: false
          - label: Imagen SEO
            name: seo_image
            widget: image
            required: false
          - label: Entradilla
            name: tagline
            widget: markdown
      - label: Servicios
        name: services
        file: src/data/pages/servicios.md
        fields:
          - label: Template
            name: template
            widget: hidden
            default: projects
          - label: Título
            name: title
            widget: string
          - label: Descripción SEO
            name: seo_description
            widget: string
            required: false
          - label: Imagen SEO
            name: seo_image
            widget: image
            required: false
          - label: Entradilla
            name: tagline
            widget: markdown
      - label: Nota Legal
        name: legal
        file: src/data/pages/nota-legal.md
        fields:
          - label: Template
            name: template
            widget: hidden
            default: legal
          - label: Título
            name: title
            widget: string
          - label: Descripción SEO
            name: seo_description
            widget: string
            required: false
          - label: Imagen SEO
            name: seo_image
            widget: image
            required: false
          - label: Entradilla
            name: tagline
            widget: markdown
          - label: Texto Legal
            name: text
            widget: markdown
      - label: Construcciones singulares
        name: products
        file: src/data/pages/construcciones-singulares.md
        fields:
          - label: Template
            name: template
            widget: hidden
            default: products
          - label: Título
            name: title
            widget: string
          - label: Descripción SEO
            name: seo_description
            widget: string
            required: false
          - label: Imagen SEO
            name: seo_image
            widget: image
            required: false
          - label: Entradilla
            name: tagline
            widget: markdown
      - label: Empresa
        name: company
        file: src/data/pages/empresa.md
        fields:
          - label: Template
            name: template
            widget: hidden
            default: company
          - label: Título
            name: title
            widget: string
          - label: Descripción SEO
            name: seo_description
            widget: string
            required: false
          - label: Imagen SEO
            name: seo_image
            widget: image
            required: false
          - label: Entradilla
            name: tagline
            widget: markdown
          - label: Datos contacto
            name: contact_info
            widget: markdown
          - label: Google Map
            name: map
            widget: string
          - label: Equipo
            name: team
            widget: list
            fields:
              - label: Nombre
                name: name
                widget: string
              - label: Cargo
                name: position
                widget: string
              - label: Foto
                name: picture
                widget: image
              - label: Email
                name: email
                widget: string
          - label: Descripción
            name: description
            widget: markdown
          - label: Imagen principal
            name: picture
            widget: image
          - label: Historia
            name: timeline
            widget: list
            fields:
              - label: Año
                name: year
                widget: number
                valueType: int
              - label: Texto
                name: text
                widget: markdown
          - label: Links
            name: links
            widget: list
            fields:
              - label: Cita
                name: cite
                widget: markdown
              - label: Fuente
                name: source
                widget: string
              - label: URL
                name: url
                widget: string
              - label: Fecha
                name: date
                widget: date
  - label: Clientes
    name: clients
    folder: src/data/cliente
    editor:
      preview: false
    create: true
    fields:
      - label: Template
        name: template
        widget: hidden
        default: client
      - label: Título
        name: title
        widget: string
      - label: Logo
        name: picture
        widget: image
      - lalbel: Visible en la web
        name: visible
        widget: boolean
        default: true
  - label: Proyectos
    name: projects
    folder: src/data/proyecto
    editor:
      preview: false
    create: true
    fields:
      - label: Template
        name: template
        widget: hidden
        default: project
      - label: Título
        name: title
        widget: string
      - label: Descripción SEO
        name: seo_description
        widget: string
        required: false
      - label: Imagen SEO
        name: seo_image
        widget: image
        required: false
      - label: Entradilla
        name: tagline
        widget: markdown
      - label: Destacado
        name: highlight
        widget: boolean
      - label: Cliente
        name: related_client
        widget: relation
        collection: clients
        searchFields: ["title"]
        valueField: title
        displayFields: ["title"]
      - label: Imagen principal
        name: picture
        widget: image
      - label: Descripción listados
        name: short_description
        widget: string
        required: false
      - label: Secciones
        name: sections
        widget: list
        fields:
          - label: Título
            name: title
            widget: string
            required: false
          - label: Tipo
            name: type
            widget: select
            options: ["text", "video", "image"]
            default: text
          - label: Texto
            name: text
            widget: markdown
            required: false
          - label: Imagen
            name: image
            widget: image
            required: false
          - label: Vídeo de Youtube
            name: video
            hint: Poner sólo el id del vídeo (p. ej. oHg5SJYRHA0)
            widget: string
            required: false
      - label: Galería
        name: gallery
        widget: list
        fields:
          - label: Título
            name: title
            widget: string
          - label: Imagen
            name: image
            widget: image
      - label: Links
        name: links
        widget: list
        fields:
          - label: Cita
            name: cite
            widget: markdown
          - label: Fuente
            name: source
            widget: string
          - label: URL
            name: url
            widget: string
          - label: Fecha
            name: date
            widget: date
  - label: Servicios
    name: services
    folder: src/data/servicio
    editor:
      preview: false
    create: true
    fields:
      - label: Template
        name: template
        widget: hidden
        default: service
      - label: Título
        name: title
        widget: string
      - label: Descripción SEO
        name: seo_description
        widget: string
        required: false
      - label: Imagen SEO
        name: seo_image
        widget: image
        required: false
      - label: Imagen principal
        name: picture
        widget: image
      - label: Descripción corta
        name: short_description
        widget: string
      - label: Descripción
        name: description
        widget: markdown
      - label: Detalles
        name: details
        widget: list
        fields:
          - label: Título
            name: title
            widget: string
          - label: Imagen
            name: image
            widget: image
          - label: Texto
            name: text
            widget: markdown
      - label: Galería
        name: gallery
        widget: list
        fields:
          - label: Título
            name: title
            widget: string
          - label: Imagen
            name: image
            widget: image
      - label: Tarifas
        name: prices
        widget: list
        fields:
          - label: Nombre
            name: name
            widget: string
          - label: Descripción
            name: description
            widget: string
          - label: Precio
            name: price
            widget: number
            valueType: float
            required: false
          - label: Unidad
            name: unit
            widget: string
            default: €
            required: false
          - label: Solicitar presupuesto
            name: budget
            hint: Marcar para que no aparezca el precio sino un botón que abre un formulario de solicitar presupuesto
            widget: boolean
            default: false
            required: false
          - label: Ayuda presupuesto
            name: template
            widget: text
            required: false
            hint: Este texto aparecerá en la caja de comentarios del formulario de petición de presupuesto
      - label: Proyectos Destacados
        name: related_projects
        widget: list
        fields:
          - label: Proyecto
            name: project
            widget: relation
            collection: projects
            searchFields: ["title"]
            valueField: title
            displayFields: ["title"]
  - label: Construcción
    name: products
    folder: src/data/construccion
    editor:
      preview: false
    create: true
    fields:
      - label: Template
        name: template
        widget: hidden
        default: product
      - label: Título
        name: title
        widget: string
      - label: Descripción SEO
        name: seo_description
        widget: string
        required: false
      - label: Imagen SEO
        name: seo_image
        widget: image
        required: false
      - label: Destacado
        name: highlight
        widget: boolean
      - label: Imagen principal
        name: picture
        widget: image
      - label: Imagen listados
        name: alt_picture
        widget: image
      - label: Descripción
        name: description
        widget: markdown
      - label: Descripción listados
        name: short_description
        widget: string
      - label: Galería
        name: gallery
        widget: list
        fields:
          - label: Título
            name: title
            widget: string
          - label: Imagen
            name: image
            widget: image
      - label: Detalles compra
        name: buy_details
        widget: markdown
      - label: Precio
        name: price
        widget: number
        valueType: float
        required: false
