name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Publish on production
    runs-on: ubuntu-latest
    steps:
      - name: Execute SSH commmands on remote server
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ls -lha
          host: sat.grupofutures.com
          username: futures
          privateKey: ${{ secrets.KEY}}